# Generated by Django 5.0.1 on 2024-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='hardwareImages/default.png', null=True, upload_to='hardwareImages/'),
        ),
    ]
